backends = ["vfox:mise-plugins/vfox-android-sdk"]
bins = [
  "apkanalyzer",
  "avdmanager",
  "d8",
  "lint",
  "profgen",
  "r8",
  "resourceshrinker",
  "retrace",
  "screenshot2",
  "sdkmanager",
]
description = "Android Command-line tools"
test = { cmd = "sdkmanager --version", expected = ".0", tools = ["java"] }
version_order = "source"
