description = "ansible python package contains the core runtime and CLI tools, such as ansible and ansible-playbook and extra modules, plugins, and roles"
test = { cmd = "ansible --version", expected = "ansible" }

[[backends]]
full = "uv:ansible"

[backends.options]
uv_tool_args = "--with-executables-from ansible-core,ansible-lint"
