backends = ["aqua:chainguard-dev/apko", "asdf:omissis/asdf-apko"]
bins = ["apko"]
description = "Build OCI images from APK packages directly without Dockerfile"
test = { cmd = "apko version", expected = "GitVersion:    v{{version}}" }
version_order = "semver"
