description = "Aspire is the tool for code-first, extensible, observable dev and deploy."
test = { cmd = "aspire --version", expected = "{{version}}" }
version_order = "semver"

backends = [{ full = "github:microsoft/aspire", attestations_since = "13.5.2" }]
bins = ["aspire"]
