backends = ["aqua:ByteNess/aws-vault"]
description = "A vault for securely storing and accessing AWS credentials in development environments"
# test = ["aws-vault --version", "v{{version}}"] # TODO: re-enable after versions host update
