aliases = ["azure-cli"]
description = "azure-cli (az)"
test = { cmd = "az --version", expected = "azure-cli                         {{version}}" }

[[backends]]
full = "uv:azure-cli"

[backends.options]
uv_tool_args = "--prerelease=allow"
