backends = ["gem:bashly"]
description = "Bashly is a command line application (written in Ruby) that lets you generate feature-rich bash command line tools"
# test = ["bashly --version", "{{version}}"]  # not working in CI
