backends = ["aqua:mathew-fleisch/bashbot", "asdf:mathew-fleisch/asdf-bashbot"]
bins = ["bashbot"]
description = "A slack-bot written in golang for infrastructure/devops teams"
test = { cmd = "bashbot version", expected = "v{{version}}" }
version_order = "semver"
