backends = ["aqua:eth-p/bat-extras", "asdf:mise-plugins/mise-bat-extras"]
bins = [
  "bat-modules",
  "batdiff",
  "batgrep",
  "batman",
  "batpipe",
  "batwatch",
  "prettybat",
]
description = "Bash scripts that integrate bat with various command line tools"
test = { cmd = "batman --version", expected = "batman {{version}}" }
version_order = "source"
