backends = ["aqua:betterleaks/betterleaks", "github:betterleaks/betterleaks"]
description = "Betterleaks scans code, past or present, for secrets"
test = { cmd = "betterleaks --version", expected = "betterleaks version {{version}}" }
