backends = ["github:btraceio/btrace", "asdf:mise-plugins/mise-btrace"]
description = "BTrace - a safe, dynamic tracing tool for the Java platform"
test = { cmd = "env JAVA_HOME=/usr/lib/jvm/default-java btrace --version", expected = "BTrace v.{{version}}" }
