backends = ["core:bun"]
description = "Bun is a fast JavaScript all-in-one toolkit"
detect = ["bun.lock", "bun.lockb", "bunfig.toml"]
idiomatic_files = [".bun-version", "package.json"]
test = { cmd = "bun --version", expected = "{{version}}" }
