backends = [
  "aqua:sagiegurari/cargo-make",
  "asdf:mise-plugins/asdf-cargo-make",
  "cargo:cargo-make",
]
bins = ["cargo-make", "makers"]
description = "Rust task runner and build tool"
test = { cmd = "makers --version", expected = "cargo-make {{version}}" }
version_order = "semver"
