backends = ["github:ccache/ccache", "asdf:asdf-community/asdf-ccache"]
bins = ["ccache"]
description = "ccache – a fast compiler cache"
test = { cmd = "ccache --version", expected = "ccache version {{version}}" }
version_order = "source"
