backends = ["aqua:checkmake/checkmake"]
bins = ["checkmake"]
description = "Linter/analyzer for Makefiles"
test = { cmd = "checkmake --version", expected = "checkmake v{{version}}" }
version_order = "semver"
