backends = ["aqua:checkstyle/checkstyle"]
description = "Checks Java source code against a coding standard"
test = { cmd = 'java -jar "$(command -v checkstyle)" --version', expected = "Checkstyle version: {{version}}", tools = [
  "java",
] }
