backends = ["aqua:cloudsmith-io/cloudsmith-cli"]
bins = ["cloudsmith"]
description = "Official Cloudsmith Command-Line Interface"
test = { cmd = "cloudsmith --version", expected = "CLI Package Version" }
version_order = "semver"
