backends = ["aqua:open-policy-agent/conftest", "asdf:looztra/asdf-conftest"]
bins = ["conftest"]
description = "Write tests against structured configuration data using the Open Policy Agent Rego query language"
version_order = "semver"
