backends = [
  { full = "github:uutils/coreutils", platforms = [
    "linux-arm",
  ] },
  "aqua:uutils/coreutils",
]
bins = ["coreutils"]
description = "Cross-platform Rust rewrite of the GNU coreutils"
version_order = "semver"
