backends = ["aqua:schollz/croc"]
bins = ["croc"]
description = "Easily and securely send things from one computer to another 🐊 📦"
test = { cmd = "croc --version", expected = "croc version {{version}}" }
version_order = "semver"
