aliases = ["crossplane-cli"]
backends = ["aqua:crossplane/crossplane", "asdf:joke/asdf-crossplane-cli"]
bins = ["crossplane"]
description = "The Crossplane CLI extends kubectl with functionality to build, push, and install Crossplane packages"
version_order = "semver"
