backends = ["aqua:dependency-check/DependencyCheck"]
description = "OWASP dependency-check is a software composition analysis utility that detects publicly disclosed vulnerabilities in application dependencies"
test = { cmd = "dependency-check --version", expected = "Dependency-Check Core version {{version}}" }
