backends = ["aqua:goodwithtech/dockle", "asdf:mathew-fleisch/asdf-dockle"]
bins = ["dockle"]
description = "Container Image Linter for Security, Helping build the Best-Practice Docker Image, Easy to start"
version_order = "semver"
