backends = [
  "aqua:editorconfig-checker/editorconfig-checker",
  "asdf:gabitchov/asdf-editorconfig-checker",
]
bins = ["ec"]
description = "A tool to verify that your files are in harmony with your .editorconfig"
test = { cmd = "ec --version", expected = "v{{version}}" }
version_order = "semver"
