backends = ["github:floeorg/floe"]
description = "A functional language with full TypeScript interop"
os = ["linux", "macos", "windows"]
test = { cmd = "floe --version", expected = "floe {{version}}" }
