backends = ["aqua:controlplaneio-fluxcd/flux-operator/flux-operator-mcp"]
description = "GitOps on Autopilot Mode - MCP"
test = { cmd = "flux-operator-mcp --version", expected = "flux-operator-mcp version {{version}}" }
