backends = ["aqua:junegunn/fzf", "asdf:kompiro/asdf-fzf"]
bins = ["fzf"]
description = ":cherry_blossom: A command-line fuzzy finder"
test = { cmd = "fzf --version", expected = "{{version}}" }
version_order = "semver"
