description = "command line management for Google Workspace"
# test = { cmd = "gam version", expected = "GAM {{version}}" }

[[backends]]
full = "github:GAM-team/GAM"

[[backends]]
full = "asdf:offbyone/asdf-gam"
