backends = [
  "vfox:jdx/vfox-gcc-arm-none-eabi",
  "asdf:mise-plugins/mise-gcc-arm-none-eabi",
]
bins = [
  "arm-none-eabi-addr2line",
  "arm-none-eabi-ar",
  "arm-none-eabi-as",
  "arm-none-eabi-c++",
  "arm-none-eabi-c++filt",
  "arm-none-eabi-cpp",
  "arm-none-eabi-elfedit",
  "arm-none-eabi-g++",
  "arm-none-eabi-gcc",
  "arm-none-eabi-gcc-ar",
  "arm-none-eabi-gcc-nm",
  "arm-none-eabi-gcc-ranlib",
  "arm-none-eabi-gcov",
  "arm-none-eabi-gcov-dump",
  "arm-none-eabi-gcov-tool",
  "arm-none-eabi-gdb",
  "arm-none-eabi-gdb-add-index",
  "arm-none-eabi-gdb-add-index-py",
  "arm-none-eabi-gdb-py",
  "arm-none-eabi-gfortran",
  "arm-none-eabi-gprof",
  "arm-none-eabi-ld",
  "arm-none-eabi-ld.bfd",
  "arm-none-eabi-lto-dump",
  "arm-none-eabi-nm",
  "arm-none-eabi-objcopy",
  "arm-none-eabi-objdump",
  "arm-none-eabi-ranlib",
  "arm-none-eabi-readelf",
  "arm-none-eabi-size",
  "arm-none-eabi-strings",
  "arm-none-eabi-strip",
]
description = "Arm GNU Toolchain"
