backends = ["pipx:git-filter-repo"]
depends = ["git"]
description = "Quickly rewrite git repository history (filter-branch replacement)"
test = { cmd = "which git-filter-repo", expected = "git-filter-repo" }
