aliases = ["gh"]
backends = [
  "aqua:cli/cli",
  "github:cli/cli",
  "asdf:bartlomiejdanek/asdf-github-cli",
]
description = "GitHub’s official command line tool"
test = { cmd = "gh --version", expected = "gh version {{version}}" }
