description = "gitlab cli"
test = { cmd = "glab version", expected = "glab {{version}}" }
version_order = "semver"

bins = ["glab"]
[[backends]]
full = "gitlab:gitlab-org/cli"
platforms = ["linux", "macos"]

[[backends]]
full = "gitlab:gitlab-org/cli"
platforms = ["windows"]

[[backends]]
full = "asdf:mise-plugins/mise-glab"
