backends = ["aqua:golangci/golangci-lint", "asdf:hypnoglow/asdf-golangci-lint"]
bins = ["golangci-lint"]
description = "Fast linters Runner for Go"
idiomatic_files = [
  { path = ".golangci.yml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = ".golangci.yaml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = ".golangci.toml", version_regex = '''(?m)^\s*version\s*=\s*["']?v?([0-9]+)''' },
  { path = ".golangci.json", version_json_path = ".version" },
]
version_order = "source"
