backends = ["aqua:goreleaser/goreleaser", "asdf:kforsthoevel/asdf-goreleaser"]
description = "Deliver Go binaries as fast and easily as possible"
idiomatic_files = [
  { path = ".config/goreleaser.yml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = ".config/goreleaser.yaml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = ".goreleaser.yml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = ".goreleaser.yaml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = "goreleaser.yml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
  { path = "goreleaser.yaml", version_regex = '''(?m)^\s*version\s*:\s*["']?v?([0-9]+)''' },
]
