backends = ["vfox:jdx/vfox-graalvm", "asdf:mise-plugins/mise-graalvm"]
bins = [
  "jar",
  "jarsigner",
  "java",
  "javac",
  "javadoc",
  "javap",
  "jcmd",
  "jconsole",
  "jdb",
  "jdeprscan",
  "jdeps",
  "jfr",
  "jhsdb",
  "jimage",
  "jinfo",
  "jlink",
  "jmap",
  "jmod",
  "jnativescan",
  "jpackage",
  "jps",
  "jrunscript",
  "jshell",
  "jstack",
  "jstat",
  "jstatd",
  "jwebserver",
  "keytool",
  "native-image",
  "native-image-configure",
  "rmiregistry",
  "serialver",
]
description = "An advanced JDK with ahead-of-time Native Image compilation"
