description = "Grok Build is an agentic coding tool that runs in your terminal"
os = ["linux", "macos", "windows"]
test = { cmd = "grok --version", expected = "{{version}}" }

bins = ["grok"]
[[backends]]
full = "http:grok"

[backends.options]
bin = "grok"
url = 'https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-{{ os() }}-{{ arch(x64="x86_64", arm64="aarch64") }}'
version_list_url = "https://x.ai/cli/stable"

[backends.options.platforms.windows-arm64]
bin = "grok.exe"
url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-aarch64.exe"

[backends.options.platforms.windows-x64]
bin = "grok.exe"
url = "https://storage.googleapis.com/grok-build-public-artifacts/cli/grok-{{ version }}-windows-x86_64.exe"

[[backends]]
full = "aqua:x.ai/cli/grok"
