backends = [
  "aqua:grpc-ecosystem/grpc-health-probe",
  "asdf:zufardhiyaulhaq/asdf-grpc-health-probe",
]
bins = ["grpc_health_probe"]
description = "A command-line tool to perform health-checks for gRPC applications in Kubernetes and elsewhere"
os = ["linux", "macos"]
test = { cmd = "grpc_health_probe --version", expected = "{{version}}" }
version_order = "semver"
