backends = ["github:HaxeFoundation/haxe", "asdf:mise-plugins/mise-haxe"]
bins = ["haxe", "haxelib"]
depends = ["neko"]
description = "Haxe - The Cross-Platform Toolkit"
test = { cmd = "haxe --version", expected = "{{version}}" }
version_order = "source"
