description = "Incus is a modern, secure and powerful system container and virtual machine manager"
os = ["linux", "macos", "windows", "freebsd"]
test = { cmd = "incus --version", expected = "{{ version | split(pat='.') | slice(start=0, end=2) | join(sep='.') }}" }

[[backends]]
full = "aqua:lxc/incus"
platforms = ["linux", "macos", "windows"]

[[backends]]
full = "github:lxc/incus"

[backends.options]
asset_pattern = "bin.{{ os() }}.incus.{{ arch(x64='x86_64', arm64='aarch64') }}{% if os() == 'windows' %}.exe{% endif %}"
bin = "incus"

[backends.options.platforms.windows-x64]
bin = "incus.exe"

[backends.options.platforms.windows-arm64]
bin = "incus.exe"
