description = "Incus migrate imports existing systems into Incus"
os = ["linux"]
test = { cmd = "incus-migrate --version", expected = "{{ version | split(pat='.') | slice(start=0, end=2) | join(sep='.') }}" }

[[backends]]
full = "github:lxc/incus"

[backends.options]
asset_pattern = "bin.linux.incus-migrate.{{ arch(x64='x86_64', arm64='aarch64') }}"
bin = "incus-migrate"
