backends = ["aqua:jmespath/jp", "asdf:skyzyx/asdf-jmespath"]
bins = ["jp"]
description = "Command line interface to JMESPath - http://jmespath.org"
test = { cmd = "jp --version", expected = "jp version {{version}}" }
