description = "A command line UI for decoding/encoding JSON Web Tokens"
# test = { cmd = "jwtui --version", expected = "jwt-ui {{version}}" }

[[backends]]
full = "github:jwt-rs/jwt-ui"

[[backends]]
full = "cargo:jwt-ui"
