description = "Kiro CLI is an agentic coding tool that lives in your terminal"
os = ["linux", "macos"]
test = { cmd = "kiro-cli --version", expected = "kiro-cli {{version}}" }
version_order = "source"

bins = ["kiro-cli", "kiro-cli-chat"]
[[backends]]
full = "http:kiro-cli"
platforms = ["linux-x64", "linux-arm64"]

[backends.options]
bin_path = "kirocli/bin"
checksum_expr = '"sha256:" + filter(fromJSON(body).packages, { #.download endsWith filename })[0].sha256'
checksum_url = "https://prod.download.cli.kiro.dev/stable/latest/manifest.json"
url = 'https://prod.download.cli.kiro.dev/stable/{{ version }}/kirocli-{{ arch(x64="x86_64", arm64="aarch64") }}-linux-musl.zip'
version_json_path = ".version"
version_list_url = "https://prod.download.cli.kiro.dev/stable/latest/manifest.json"

[[backends]]
full = "aqua:kiro.dev/kiro-cli"
platforms = ["macos"]
