backends = ["aqua:lima-vm/lima", "asdf:CrouchingMuppet/asdf-lima"]
description = "Linux virtual machines, with a focus on running containers"
# TODO: re-enable once limactl exposes a version command that works as root in CI.
# test = { cmd = "limactl --version", expected = "limactl version {{version}}" }
