description = "The LocalStack CLI packaged using pyinstaller"
test = { cmd = "localstack --version", expected = "LocalStack CLI {{version}}" }

backends = [
  "aqua:localstack/localstack-cli",
  "github:localstack/localstack-cli",
]
