backends = ["aqua:lycheeverse/lychee", "cargo:lychee"]
bins = ["lychee"]
description = "Fast, async, stream-based link checker written in Rust. Finds broken URLs and mail addresses inside Markdown, HTML, reStructuredText, websites and more"
test = { cmd = "lychee --version", expected = "lychee {{version}}" }
version_order = "semver"
