backends = [
  "aqua:kovetskiy/mark",
  "github:kovetskiy/mark",
  "asdf:jfreeland/asdf-mark",
]
bins = ["mark"]
description = "Sync your markdown files with Confluence pages"
test = { cmd = "mark --version", expected = "{{version}}" }
version_order = "source"
