backends = [
  "aqua:apache/maven",
  "asdf:mise-plugins/mise-maven",
  "vfox:jdx/vfox-maven",
]
bins = ["mvn", "mvnDebug", "mvnyjp"]
description = "Apache Maven core"
test = { cmd = "mvn --version", expected = "Apache Maven {{version}}" }
version_order = "semver"
