backends = [
  "aqua:AlexanderGrooff/mermaid-ascii",
  { full = "github:AlexanderGrooff/mermaid-ascii", attestations_since = "1.6.0" },
]
description = "Render Mermaid graphs inside your terminal"
test = { cmd = "which mermaid-ascii", expected = "mermaid-ascii" }
version_order = "semver"
