description = "A modern, JVM-based, full-stack framework for building modular, easily testable microservice and serverless applications"
version_order = "semver"
# test = { cmd = "mn --version", expected = "Micronaut Version: {{version}}" }

bins = ["mn"]
[[backends]]
full = "github:micronaut-projects/micronaut-starter"

[[backends]]
full = "asdf:mise-plugins/mise-micronaut"
