backends = ["aqua:svenstaro/miniserve"]
description = "For when you really just want to serve some files over HTTP right now!"
test = { cmd = "miniserve --version", expected = "miniserve {{version}}" }
