backends = ["aqua:metalbear-co/mirrord", "asdf:metalbear-co/asdf-mirrord"]
bins = ["mirrord"]
description = "Connect your local process and your cloud environment, and run local code in cloud conditions"
version_order = "semver"
# test = ["mirrord --version", "mirrord {{version}}"]
