bins = ["mo", "mole"]
description = "Deep clean and optimize your Mac"
os = ["macos"]
test = { cmd = "mo --version", expected = "Mole version {{version}}" }
version_order = "semver"

[[backends]]
full = "github:tw93/Mole"
min_version = "1.16.1"

[backends.options]
additional_asset_patterns = ['binaries-darwin-{{ arch(x64="amd64") }}.tar.gz']
bin_path = "."
filter_bins = ["mo", "mole"]
postinstall = '''
set -eu
cd "$MISE_TOOL_INSTALL_PATH"
mv analyze-darwin-* bin/analyze-go
mv status-darwin-* bin/status-go
ln -s ../lib ../bin .mise-bins/
'''
strip_components = 1
version_prefix = "V"

[backends.options.platforms]
macos-arm64 = { url = "https://github.com/tw93/Mole/archive/refs/tags/V{{ version }}.tar.gz" }
macos-x64 = { url = "https://github.com/tw93/Mole/archive/refs/tags/V{{ version }}.tar.gz" }
