description = "A build system and monorepo management tool for the web ecosystem, written in Rust"
backends = ["aqua:moonrepo/moon"]
idiomatic_files = [".moon/*"]

[test]
cmd = "moon --version"
expected = "moon {{ version }}"
