backends = ["github:nats-io/nats-server"]
bins = ["nats-server"]
description = "High-Performance server for NATS.io, the cloud and edge native messaging system"
test = { cmd = "nats-server --version", expected = "v{{version}}" }
version_order = "semver"
