aliases = ["nodejs"]
backend_aliases = ["nodejs"]
backends = ["core:node"]
description = "Node.js® is a free, open-source, cross-platform JavaScript runtime environment that lets developers create servers, web apps, command line tools and scripts (Builtin plugin)"
detect = ["package.json", ".nvmrc", ".node-version"]
