backends = ["github:openfga/openfga"]
description = "A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar"
test = { cmd = "openfga version 2>&1", expected = "v{{version}}" }
