backends = [
  { full = "github:jgm/pandoc", attestations_since = "3.10.1" },
  "asdf:Fbrisset/asdf-pandoc",
]
bins = ["pandoc", "pandoc-lua", "pandoc-server"]
description = "Universal markup converter"
version_order = "source"
