backends = ["aqua:jgm/pandoc", "github:jgm/pandoc", "asdf:Fbrisset/asdf-pandoc"]
bins = ["pandoc", "pandoc-lua", "pandoc-server"]
description = "Universal markup converter"
test = { cmd = "pandoc --version", expected = "pandoc {{version}}" }
version_order = "source"
