backends = [
  { full = "packslip:github.com/jdx/pitchfork", min_version = "2.24.2", options = { identity = "https://github.com/jdx/pitchfork/.github/workflows/release.yml@refs/heads/main", issuer = "https://token.actions.githubusercontent.com" } },
  "aqua:jdx/pitchfork",
]
bins = ["pitchfork"]
description = "Daemons with DX"
test = { cmd = "pitchfork --version", expected = "pitchfork {{version}}" }
version_order = "semver"
