backends = ["aqua:apple/pkl", "github:apple/pkl", "asdf:mise-plugins/asdf-pkl"]
description = "A configuration as code language with rich validation and tooling"
test = { cmd = "pkl --version", expected = "Pkl {{version}}" }
