backends = [
  { full = "aqua:pnpm/pnpm", options = { version_order = "semver" } },
  "npm:pnpm",
]
bins = ["pn", "pnpm", "pnpx", "pnx"]
description = "Fast, disk space efficient package manager"
detect = ["pnpm-lock.yaml", "pnpm-workspace.yaml"]
idiomatic_files = ["package.json"]
test = { cmd = "pnpm --version", expected = "{{version}}" }
