backends = [
  "conda:postgresql",
  "vfox:mise-plugins/vfox-postgres",
  "asdf:mise-plugins/mise-postgres",
]
bins = [
  "clusterdb",
  "createdb",
  "createuser",
  "dropdb",
  "dropuser",
  "ecpg",
  "initdb",
  "oid2name",
  "pg_amcheck",
  "pg_archivecleanup",
  "pg_basebackup",
  "pg_checksums",
  "pg_combinebackup",
  "pg_controldata",
  "pg_createsubscriber",
  "pg_ctl",
  "pg_dump",
  "pg_dumpall",
  "pg_isready",
  "pg_receivewal",
  "pg_recvlogical",
  "pg_resetwal",
  "pg_restore",
  "pg_rewind",
  "pg_test_fsync",
  "pg_test_timing",
  "pg_upgrade",
  "pg_verifybackup",
  "pg_waldump",
  "pg_walsummary",
  "pgbench",
  "postgres",
  "psql",
  "reindexdb",
  "vacuumdb",
  "vacuumlo",
]
description = "PostgreSQL is a powerful, open source object-relational database system with over 35 years of active development that has earned it a strong reputation for reliability, feature robustness, and performance"
test = { cmd = "postgres --version", expected = "{{version}}" }
version_order = "source"
