backends = ["aqua:prometheus/prometheus", "asdf:asdf-community/asdf-promtool"]
bins = ["prometheus", "promtool"]
description = "The Prometheus monitoring system and time series database"
test = { cmd = "promtool --version", expected = "promtool, version {{version}}" }
version_order = "semver"
