description = "This directory contains the JavaScript Protocol Buffers runtime library"
# test = { cmd = "protoc-gen-js --version", expected = "protoc-gen-js version {{version}}" }

[[backends]]
full = "github:protocolbuffers/protobuf-javascript"

[[backends]]
full = "asdf:pbr0ck3r/asdf-protoc-gen-js"
