backends = ["aqua:regclient/regclient/regsync", "asdf:rsrchboy/asdf-regsync"]
bins = ["regsync"]
description = "regsync is a registry synchronization utility used to update mirrors of OCI compatible container registries"
