backends = ["aqua:sqshq/sampler"]
bins = ["sampler"]
description = "Tool for shell commands execution, visualization and alerting. Configured with a simple YAML file"
test = { cmd = "sampler --version", expected = "{{version}}" }
version_order = "semver"
