depends = ["java"]
description = "Free database schema discovery and comprehension tool"
# test = { cmd = "schemacrawler.sh --version", expected = "SchemaCrawler {{version}}" }

[[backends]]
full = "github:schemacrawler/SchemaCrawler"
