depends = ["java"]
description = "Free database schema discovery and comprehension tool"
version_order = "source"
# test = { cmd = "schemacrawler.sh --version", expected = "SchemaCrawler {{version}}" }

bins = ["schemacrawler.sh"]
[[backends]]
full = "github:schemacrawler/SchemaCrawler"
