backends = [
  "aqua:rossmacarthur/sheldon",
  "github:rossmacarthur/sheldon",
  "cargo:sheldon",
]
description = "Fast, configurable, shell plugin manager"
os = ["linux", "macos"]
test = { cmd = "sheldon --version", expected = "{{version}}" }
