backends = [
  { full = "github:sagernet/sing-box", attestations_since = "1.14.0-alpha.45" },
]
bins = ["sing-box"]
description = "The universal proxy platform"
test = { cmd = "sing-box version | head -n1 | awk '{print $3}'", expected = "{{version}}" }
version_order = "semver"
