description = "Solidity, the Smart Contract Programming Language"
# test = { cmd = "solc --version", expected = "Version: {{version}}" }

[[backends]]
full = "github:ethereum/solidity"

[backends.options]
bin = "solc"

[[backends]]
full = "asdf:diegodorado/asdf-solidity"
