backends = ["aqua:spotDL/spotify-downloader"]
bins = ["spotify-downloader"]
description = "Download your Spotify playlists and songs along with album art and metadata (from YouTube if a match is found)"
test = { cmd = "spotify-downloader --help", expected = "Download your Spotify playlists and songs" }
version_order = "semver"
