backends = ["aqua:commercialhaskell/stack", "asdf:mise-plugins/mise-ghcup"]
bins = ["stack"]
description = "The Haskell Tool Stack"
test = { cmd = "stack --version", expected = "Version {{version}}" }
version_order = "source"
