description = "Starknet testing framework (like Truffle, Hardhat and DappTools but for Starknet)"
# test = { cmd = "snforge --version", expected = "snforge {{version}}" }

[[backends]]
full = "github:foundry-rs/starknet-foundry"
