backends = [
  "aqua:dominikh/go-tools/staticcheck",
  "asdf:pbr0ck3r/asdf-staticcheck",
  "go:honnef.co/go/tools/cmd/staticcheck",
]
bins = ["staticcheck"]
description = "Staticcheck - The advanced Go linter"
test = { cmd = "staticcheck --version", expected = "staticcheck {{version}}" }
version_order = "source"
