backends = ["github:kristoff-it/superhtml"]
bins = ["superhtml"]
description = "HTML Validator, Formatter, LSP, and Templating Language Library"
test = { cmd = "superhtml version", expected = "{{version}}" }
