backends = ["vfox:jdx/vfox-tinytex", "asdf:mise-plugins/mise-tinytex"]
bins = [
  "afm2tfm",
  "allcm",
  "allec",
  "allneeded",
  "biber",
  "bibtex",
  "dvi2fax",
  "dvilualatex",
  "dviluatex",
  "dvipdfm",
  "dvipdfmx",
  "dvipdft",
  "dvips",
  "dvired",
  "e2pall",
  "ebb",
  "epstopdf",
  "etex",
  "extractbb",
  "fmtutil",
  "fmtutil-sys",
  "fmtutil-user",
  "gftodvi",
  "gftopk",
  "gftype",
  "hyperxmp-add-bytecount",
  "inimf",
  "initex",
  "kpseaccess",
  "kpsepath",
  "kpsereadlink",
  "kpsestat",
  "kpsetool",
  "kpsewhere",
  "kpsewhich",
  "kpsexpand",
  "latex",
  "latexindent",
  "latexmk",
  "luahbtex",
  "lualatex",
  "luaotfload-tool",
  "luatex",
  "makeindex",
  "mf",
  "mf-nowin",
  "mft",
  "mkindex",
  "mkocp",
  "mkofm",
  "mktexfmt",
  "mktexlsr",
  "mktexmf",
  "mktexpk",
  "mktextfm",
  "pdfetex",
  "pdflatex",
  "pdftex",
  "pktogf",
  "pktype",
  "ps2frag",
  "pslatex",
  "repstopdf",
  "rungs",
  "simpdftex",
  "teckit_compile",
  "tex",
  "texconfig",
  "texconfig-dialog",
  "texconfig-sys",
  "texcount",
  "texhash",
  "texlinks",
  "texlua",
  "texluac",
  "thumbpdf",
  "tlmgr",
  "updmap",
  "updmap-sys",
  "updmap-user",
  "urlbst",
  "xdvipdfmx",
  "xelatex",
  "xelatex-unsafe",
  "xetex",
  "xetex-unsafe",
]
description = "A lightweight, cross-platform, portable, and easy-to-maintain LaTeX distribution based on TeX Live"
