backends = ["aqua:tombi-toml/tombi"]
bins = ["tombi"]
description = "TOML Formatter / Linter / Language Server"
test = { cmd = "tombi --version", expected = "tombi {{version}}" }
version_order = "semver"
