backends = [
  "aqua:topgrade-rs/topgrade",
  { full = "github:topgrade-rs/topgrade", attestations_since = "16.1.0" },
  "cargo:topgrade",
]
description = "Upgrade all the things"
test = { cmd = "topgrade --version", expected = "topgrade {{version}}" }
version_order = "semver"
