description = "tsuru-client is a tsuru command line tool for application developers"
# test = { cmd = "tsuru version --help", expected = "display the current version" }

[[backends]]
full = "github:tsuru/tsuru-client"

[[backends]]
full = "asdf:virtualstaticvoid/asdf-tsuru"
