backends = ["aqua:version-fox/vfox"]
bins = ["vfox"]
description = "A cross-platform and extendable version manager with support for Java, Node.js, Flutter, .Net & more"
test = { cmd = "vfox --version", expected = "vfox version {{version}}" }
version_order = "semver"
