backends = ["aqua:watchexec/watchexec", "cargo:watchexec-cli"]
bins = ["watchexec"]
description = "Executes commands in response to file modifications"
test = { cmd = "watchexec --version", expected = "watchexec {{version}}" }
