backends = ["aqua:hashicorp/waypoint", "asdf:mise-plugins/mise-hashicorp"]
bins = ["waypoint"]
description = "A tool to build, deploy, and release any application on any platform"
version_order = "semver"
