description = "A command line tool for building Cloudflare Workers"
test = { cmd = "wrangler --version", expected = "{{version}}", tools = [
  "aube",
] }

[[backends]]
full = "npm:wrangler"

[backends.options]
allow_builds = ["esbuild", "sharp", "workerd"]
