description = "A command line tool for building Cloudflare Workers"
test = { cmd = "wrangler --version", expected = "{{version}}" }

[[backends]]
full = "npm:wrangler"

[backends.options]
aube_args = "--allow-build=esbuild --allow-build=sharp --allow-build=workerd"
pnpm_args = "--allow-build=esbuild --allow-build=sharp --allow-build=workerd"
