backends = ["github:xdagiz/xytz"]
bins = ["xytz"]
description = "A Beautiful YouTube Downloader/Player TUI"
test = { cmd = "xytz --version", expected = "xytz version v{{version}}" }
version_order = "semver"
