backends = ["aqua:ajeetdsouza/zoxide", "cargo:zoxide"]
bins = ["zoxide"]
description = "A smarter cd command. Supports all major shells"
test = { cmd = "zoxide --version", expected = "zoxide {{version}}" }
