self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - macos-14
    - namespace-profile-endev-macos-arm64
    - namespace-profile-endev-macos-arm64-large
    - namespace-profile-endev-macos-arm64;overrides.cache-tag=mise-pr-rust-macos
    - namespace-profile-endev-macos-arm64-large;overrides.cache-tag=mise-release-rust-macos
    - namespace-profile-endev-linux-amd64
    - namespace-profile-endev-linux-amd64-large
    - namespace-profile-endev-linux-amd64;overrides.cache-tag=mise-pr-rust-linux
    - namespace-profile-endev-linux-amd64;overrides.cache-tag=mise-pr-rust-linux-nightly
    - namespace-profile-endev-linux-amd64;overrides.cache-tag=mise-release-plz-rust-linux
    - namespace-profile-endev-linux-amd64-large;overrides.cache-tag=mise-pr-rust-linux
    - namespace-profile-endev-linux-amd64-large;overrides.cache-tag=mise-release-rust-linux
    - buildjet-32vcpu-ubuntu-2204-arm
    - buildjet-16vcpu-ubuntu-2204-arm
    - buildjet-8vcpu-ubuntu-2204-arm
    - buildjet-4vcpu-ubuntu-2204-arm
    - buildjet-2vcpu-ubuntu-2204-arm
    - buildjet-32vcpu-ubuntu-2204
    - buildjet-16vcpu-ubuntu-2204
    - buildjet-8vcpu-ubuntu-2204
    - buildjet-4vcpu-ubuntu-2204
    - buildjet-2vcpu-ubuntu-2204

# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null
