#:schema ./schema/mise.json
min_version = "2024.1.1"

[env]
_.path = ["./target/debug", "./node_modules/.bin"]

[tools]
actionlint = "latest"
age = "latest"
aube = "latest"
bun = "latest"
cargo-binstall = "latest"
communique = "latest"
"cargo:cargo-edit" = "latest"
cargo-insta = "latest"
"github:crate-ci/cargo-release" = "latest"
git-cliff = "latest"
"cargo:toml-cli" = "latest"
usage = "latest"
gh = "latest"
hk = "latest"
jq = "latest"
fd = "latest"
lua-language-server = "latest"
stylua = "latest"
"npm:markdownlint-cli" = "latest"
prettier = "3"
"npm:ajv-cli" = "latest"
pkl = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
wait-for-gh-rate-limit = "latest"
sops = "latest"
node = "24"

[task_config]
includes = ["tasks.toml", "xtasks"]
