# To test this snap package on your local Linux machine,
# Install snapcraft (`snap install snapcraft --classic`) and
# run the following commands:
#
# ```shell
# snapcraft pack
# snap install ./mise_20xx.xx.x_amd64.snap --dangerous --classic
# ```

name: mise
title: mise-en-place
version: "2026.5.3"
summary: Dev tools, env vars, and tasks in one CLI
description: |
  mise-en-place prepares your development environment before each command runs.

  - Install and switch between [dev tools](https://mise.en.dev/dev-tools/) like node, python, cmake, terraform, and [hundreds more](https://mise.en.dev/registry.html).
  - Load [environment variables](https://mise.en.dev/environments/) for each project directory.
  - Define and run [tasks](https://mise.en.dev/tasks/) used to build, test, lint, and deploy projects.

  See the [documentation](https://mise.en.dev/getting-started.html) to learn more.

license: MIT
website: https://mise.en.dev
source-code: https://github.com/jdx/mise.git
issues: https://github.com/jdx/mise/discussions
contact:
  - https://github.com/jdx/mise/discussions
  - https://phanective.org
donation:
  - https://github.com/sponsors/jdx

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:
  armhf:

base: core24

parts:
  mise:
    source: "."
    source-type: local

    plugin: rust
    rust-channel: stable

    build-packages:
      - libssl-dev
    build-attributes:
      - enable-patchelf

  update-instructions:
    plugin: dump
    source: ./packaging/snapcraft
    source-type: local
    organize:
      "mise-self-update-instructions.toml": lib/
    stage:
      - lib/

apps:
  mise:
    command: bin/mise
