#!/usr/bin/env bash

eval "$(mise activate bash)" && eval "$(mise hook-env)"
install -m 0755 /dev/null "$TMPDIR/MISE_PATH_SAFETY_CHECK"
assert_fail "cd '$TMPDIR' && command -v MISE_PATH_SAFETY_CHECK"
