#!/usr/bin/env bash

cat <<EOF >mise.toml
[tools]
dummy = 'latest'
[hooks]
enter = 'echo ENTER'
#leave = 'echo LEAVE'
cd = 'echo CD'
preinstall = 'echo PREINSTALL'
postinstall = 'echo POSTINSTALL'
EOF

assert_contains "mise i 2>&1" "PREINSTALL"
assert_contains "mise i dummy@1 2>&1" "POSTINSTALL"

eval "$(mise hook-env)"
assert_not_contains "mise hook-env 2>&1" "CD"
assert_not_contains "mise hook-env 2>&1" "ENTER"
pushd .. || exit 1
assert_not_contains "mise hook-env 2>&1" "CD"
assert_not_contains "mise hook-env 2>&1" "ENTER"
eval "$(mise hook-env)"
popd || exit 1
assert_contains "mise hook-env 2>&1" "CD"
assert_contains "mise hook-env 2>&1" "ENTER"
eval "$(mise hook-env)"
mkdir foo
cd foo || exit 1
assert_contains "mise hook-env 2>&1" "CD"
assert_not_contains "mise hook-env 2>&1" "ENTER"
