#!/usr/bin/env bash

export MISE_EXPERIMENTAL=1

test() {
	assert_contains "mise x $1 -- $2" "$3"
}

test aqua:BurntSushi/ripgrep@14.0.0 "rg --version" "ripgrep 14.0.0"
test age@1.2.0 "age --version" "v1.2.0"
test aqua:helm/helm@3.16.3 "helm version" "v3.16.3"
test aqua:crate-ci/typos@1.27.3 "typos --version" "typos-cli 1.27.3"
test aqua:biomejs/biome@2.0.0 "biome --version" "Version: 2.0.0"
test aqua:biomejs/biome@@biomejs/biome@2.0.0 "biome --version" "Version: 2.0.0"
test aqua:gruntwork-io/terragrunt@0.77.22 "terragrunt --version" "terragrunt version v0.77.22"

assert_contains "MISE_USE_VERSIONS_HOST=0 mise ls-remote aqua:sharkdp/hyperfine" "1.8.0
1.9.0
1.10.0
1.11.0"

# Test Aqua backend with mise lock
export MISE_LOCKFILE=1

cat <<EOF >mise.toml
[tools]
"age" = "1.2.0"
EOF

touch mise.lock
mise install
mise lock --force --platforms macos-arm64
assert_contains "cat mise.lock" '[[tools.age]]'
assert_contains "cat mise.lock" 'version = "1.2.0"'
assert_contains "cat mise.lock" 'backend = "aqua:FiloSottile/age"'
assert_contains "cat mise.lock" 'url = "https://github.com/FiloSottile/age/releases'
assert_contains "cat mise.lock" 'size = 4516837'
assert_contains "cat mise.lock" 'checksum = "blake3:a54d750d8599612d69bc9499b32a549506bfa1e122a051f31754b9ec4d94fc44"'
