#!/usr/bin/env bash
require_cmd cargo

assert "mise x cargo:eza-community/eza@tag:v0.18.24 -- eza --version" "eza - A modern, maintained replacement for ls
v0.18.24 [+git]
https://github.com/eza-community/eza"
assert "mise where cargo:eza-community/eza@tag:v0.18.24" \
  "$MISE_DATA_DIR/installs/cargo-eza-community-eza/tag-v0.18.24"
assert_fail "test -d $MISE_DATA_DIR/installs/cargo-eza-community-eza/ref-v0.18.24"
assert "mise outdated cargo:eza-community/eza@tag:v0.18.24" ""
