#!/usr/bin/env bash
require_cmd pipx

assert_contains "mise x pipx:black@22.6.0 -- black --version" "22.6.0"
assert_contains "mise x pipx:psf/black@24.3.0 -- black --version" "24.3.0"
assert_contains "mise x pipx:git+https://github.com/psf/black.git@24.2.0 -- black --version" "24.2.0"
assert_contains "mise x pipx:harlequin[s3]@1.24.0 -- harlequin --version" "1.24.0"
