#!/usr/bin/env bash

export MISE_EXPERIMENTAL=1

test() {
  assert_contains "mise x $1 -- $2" "$3"
}

test dotnet:GitVersion.Tool@5.12.0 "dotnet-gitversion /version" "5.12.0+Branch.support-5.x.Sha.3f75764963eb3d7956dcd5a40488c074dd9faf9e"
test dotnet:Husky@0.7.2 "husky --version" "v0.7.2" 