#!/usr/bin/env bash
set -e

# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/../assert.sh"

skip_slow_test
export MISE_RUBY_DEFAULT_PACKAGES_FILE="$ROOT/e2e/.default-gems"
export MISE_RUBY_VERBOSE_INSTALL=1


cat >Gemfile <<EOF
# frozen_string_literal: true

ruby "3.2.2"

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
EOF

mise i ruby -v
assert_contains "mise x -- ruby --version" "ruby 3.2.2"

rm Gemfile
