#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")"/../assert.sh

skip_slow_test

export MISE_RUBY_DEFAULT_PACKAGES_FILE="$HOME/.default-gems"
export MISE_RUBY_INSTALL=1

echo "ruby-3.2.1" >.ruby-version

# disable this slow test for now
mise i ruby
assert_contains "mise x -- ruby --version" "ruby 3.2.1"
