#!/usr/bin/env bash

cat <<EOF >mise.toml
[tasks.test]
run = "echo 'running test task'"
description = "This is a test task"
[tasks.another_task]
run = "echo 'running another task'"
aliases = ["alias1", "alias2"]
EOF

cat <<EOF >task_docs.md
hello world

<!-- mise-tasks -->
## \`test\`

- **Usage**: \`test\`

This is a test task.

## \`another_task\`

- **Usage**: \`another_task\`
- **Aliases**: \`alias1\`, \`alias2\`
<!-- /mise-tasks -->

hello world
EOF

mise generate task-docs --inject --output task_docs.md

assert_contains "cat task_docs.md" 'hello world

<!-- mise-tasks -->
<!-- /mise-tasks -->

hello world'
