#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap. Safe to rerun; does not start long-lived processes.
#
# Host packages are a subset of packaging/e2e/Dockerfile: enough to build mise and
# run most e2e tests (zsh/fish/direnv/python/jq/build tools). GUI libraries and
# a JDK are omitted; those belong in the dedicated e2e image.
set -euo pipefail

# Draft builds and some Cloud Agent images run as `ubuntu`, not root.
if [ "$(id -u)" -eq 0 ]; then
	SUDO=()
else
	SUDO=(sudo -n)
fi

export DEBIAN_FRONTEND=noninteractive
"${SUDO[@]}" apt-get update
"${SUDO[@]}" apt-get install -y --no-install-recommends \
	autoconf \
	bison \
	build-essential \
	ca-certificates \
	curl \
	direnv \
	fish \
	git \
	jq \
	libffi-dev \
	libicu-dev \
	libncurses-dev \
	libreadline-dev \
	libssl-dev \
	libxml2-dev \
	libyaml-dev \
	openssh-client \
	pkg-config \
	python-is-python3 \
	python3 \
	python3-pip \
	python3-venv \
	unzip \
	xz-utils \
	zlib1g-dev \
	zsh

# Root-owned cargo/rustup homes from a snapshot are not usable by `ubuntu`.
if [ "$(id -u)" -ne 0 ]; then
	if [ -d /usr/local/cargo ]; then
		"${SUDO[@]}" chmod -R a+rwX /usr/local/cargo
	fi
	if [ -d /usr/local/rustup ]; then
		"${SUDO[@]}" chmod -R a+rwX /usr/local/rustup
	fi
fi

"${SUDO[@]}" mkdir -p /tmp/fslock
"${SUDO[@]}" chmod 1777 /tmp/fslock

msrv="$(sed -n 's/^rust-version = "\(.*\)"/\1/p' Cargo.toml | head -n1)"
if [ -z "$msrv" ]; then
	echo "failed to parse rust-version from Cargo.toml" >&2
	exit 1
fi

rustup toolchain install "$msrv" --profile minimal --no-self-update -c rustfmt,clippy
rustup default "$msrv"

cargo build --all-features
"${SUDO[@]}" ln -sfn "$PWD/target/debug/mise" /usr/local/bin/mise
hash -r

export MISE_YES=1
export MISE_TRUSTED_CONFIG_PATHS="${MISE_TRUSTED_CONFIG_PATHS:-$PWD}"

if [ -z "${MISE_GITHUB_TOKEN:-}" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
	if token="$(gh auth token 2>/dev/null)"; then
		export GITHUB_TOKEN="$token"
		export MISE_GITHUB_TOKEN="$token"
	fi
fi

# Re-export gh credentials in later shells without writing the token to disk.
# Isolated e2e runs inherit MISE_GITHUB_TOKEN/GITHUB_TOKEN from the parent.
github_token_profile=/etc/profile.d/mise-dev-github-token.sh
"${SUDO[@]}" tee "$github_token_profile" >/dev/null <<'EOF'
# Generated by .cursor/install.sh — do not store secrets here.
if [ -z "${GITHUB_TOKEN:-}" ] && [ -z "${MISE_GITHUB_TOKEN:-}" ] && command -v gh >/dev/null 2>&1; then
	if token="$(gh auth token 2>/dev/null)"; then
		export GITHUB_TOKEN="$token"
		export MISE_GITHUB_TOKEN="$token"
	fi
fi
EOF
"${SUDO[@]}" chmod 644 "$github_token_profile"

eval "$(mise activate bash --shims)"
mise install
hk install --mise

# Isolated e2e PATH includes /usr/local/bin but not the agent's mise shims.
# Point at the real binaries so require_cmd node/npm works without putting
# them on /usr/bin (test_backend_missing_deps uses PATH=/usr/bin:/bin).
for cmd in node npm npx; do
	if bin="$(mise which "$cmd" 2>/dev/null)"; then
		"${SUDO[@]}" ln -sfn "$bin" "/usr/local/bin/$cmd"
	fi
done
