#!/usr/bin/env bash

export MISE_RUSTUP_HOME="$MISE_DATA_DIR/rustup"
export MISE_CARGO_HOME="$MISE_DATA_DIR/cargo"

assert_contains "mise x rust@1.81.0 -- rustc --version" "rustc 1.81.0"

cat <<EOF >rust-toolchain.toml
[toolchain]
channel = "1.81.0"
EOF

assert_contains "mise x -- rustc --version" "rustc 1.81.0"
