#!/usr/bin/env bash

echo "golang 1.20" >.tool-versions
mkdir 21
echo "golang 1.21" >21/.tool-versions

export MISE_GO_SET_GOPATH=1

eval "$(mise activate bash)"
_mise_hook

GO_20=$(mise latest golang@1.20)
GO_21=$(mise latest golang@1.21)

mise i golang@1.20 golang@1.21 && _mise_hook

# GOPATH lives in each version's installation directory
GO_20_DIR=$(mise where "golang@$GO_20")
GO_21_DIR=$(mise where "golang@$GO_21")
[[ $GO_20_DIR != "$GO_21_DIR" ]] || fail "go $GO_20 and $GO_21 share $GO_20_DIR"

assert "go env GOPATH" "$GO_20_DIR/packages"
cd 21 && _mise_hook
assert "go env GOPATH" "$GO_21_DIR/packages"
cd .. && _mise_hook
assert "go env GOPATH" "$GO_20_DIR/packages"
