use eyre::Result;
use indoc::indoc;

/// Print `use_mise`, a direnv function that loads mise inside direnv
///
/// Running mise inside direnv is unsupported. To move a project from direnv to mise,
/// see https://mise.jdx.dev/direnv.html.
#[derive(Debug, usage_rs::Args)]
#[usage(
    hide = true,
    verbatim_doc_comment,
    example(
        "mise direnv activate > ~/.config/direnv/lib/use_mise.sh",
        help = "Install the function; then put `use mise` in .envrc and run `direnv allow`"
    )
)]
pub(super) struct DirenvActivate {}

impl DirenvActivate {
    pub(super) async fn run(self) -> Result<()> {
        miseprintln!(
            //       source_env "$(mise direnv envrc "$@")"
            indoc! {r#"
                ### Do not edit. This was autogenerated by 'mise direnv' ###
                use_mise() {{
                  direnv_load mise direnv exec
                }}
            "#}
        );

        Ok(())
    }
}
