#!/usr/bin/env bash

unset MISE_LOCKFILE

cat <<EOF >mise.toml
[settings]
lockfile = true
EOF

assert "test ! -e mise.lock"
mise use --pin tiny@1
assert "test -f mise.lock"
assert_contains "cat mise.lock" 'version = "1.1.0"'

mise use --global --pin tiny@2
assert "test ! -e $MISE_CONFIG_DIR/mise.lock"

rm mise.lock
cat <<EOF >mise.toml
[tools]
tiny = "1"
EOF

mise install
assert "test ! -e mise.lock"
