use crate::config::Config;
use crate::task::Task;
use crate::{dirs, file};
use std::path::PathBuf;

/// Generate AI prompt files from mise tasks
///
/// Creates `.prompt.md` files in `.github/prompts/` (or a custom directory)
/// for each visible mise task. These files act as slash commands in
/// AI coding assistants like GitHub Copilot and the Copilot CLI.
///
/// For example, a task named "test" with `run = "cargo test"` becomes
/// `/test` in Copilot chat. The generated prompt tells the AI assistant
/// what command to run, what the task does, and how to handle failures.
///
/// Tasks with `hide = true` are skipped. Task dependencies are included
/// in the generated prompts so the AI knows to run prerequisites.
#[derive(Debug, clap::Args)]
#[clap(verbatim_doc_comment, after_long_help = AFTER_LONG_HELP)]
pub struct Prompts {
    /// Output directory for generated prompt files
    ///
    /// Defaults to `.github/prompts/` in the current working directory.
    #[clap(long, short, verbatim_doc_comment, value_hint = clap::ValueHint::DirPath)]
    output: Option<PathBuf>,

    /// Generate a single combined prompt file instead of one per task
    #[clap(long, short = 'S', verbatim_doc_comment)]
    single: bool,

    /// Only generate prompts for tasks matching this glob pattern
    #[clap(long, short, verbatim_doc_comment)]
    pattern: Option<String>,

    /// Print to stdout instead of writing files
    #[clap(long, verbatim_doc_comment)]
    dry_run: bool,
}

impl Prompts {
    pub async fn run(self) -> eyre::Result<()> {
        let config = Config::get().await?;
        let tasks = config.tasks().await?;

        let visible_tasks: Vec<&Task> = tasks
            .values()
            .filter(|t| !t.hide)
            .filter(|t| {
                if let Some(ref pat) = self.pattern {
                    t.name.contains(pat.as_str())
                } else {
                    true
                }
            })
            .collect();

        if visible_tasks.is_empty() {
            warn!("no visible tasks found");
            return Ok(());
        }

        let output_dir = self.output.clone().unwrap_or_else(|| {
            let cwd = dirs::CWD.as_ref().expect("could not determine cwd");
            cwd.join(".github").join("prompts")
        });

        if self.single {
            let content = self.render_combined(&visible_tasks);
            if self.dry_run {
                miseprintln!("{content}");
            } else {
                let path = output_dir.join("tasks.prompt.md");
                file::create_dir_all(&output_dir)?;
                file::write(&path, &content)?;
                info!("wrote {}", path.display());
            }
        } else {
            if !self.dry_run {
                file::create_dir_all(&output_dir)?;
            }
            for task in &visible_tasks {
                let content = self.render_task_prompt(task, &tasks);
                let filename = format!(
                    "{}.prompt.md",
                    task.name.replace([':', '/'], "-")
                );
                if self.dry_run {
                    miseprintln!("--- {} ---", filename);
                    miseprintln!("{content}");
                    miseprintln!();
                } else {
                    let path = output_dir.join(&filename);
                    file::write(&path, &content)?;
                    info!("wrote {}", path.display());
                }
            }
        }

        Ok(())
    }

    fn render_task_prompt(
        &self,
        task: &Task,
        all_tasks: &std::collections::BTreeMap<String, Task>,
    ) -> String {
        let mut lines = Vec::new();

        // YAML frontmatter
        lines.push("---".to_string());
        lines.push(format!(
            "description: \"{}\"",
            Self::build_description(task)
        ));
        lines.push("tools: ['terminal']".to_string());
        lines.push("---".to_string());
        lines.push(String::new());

        // Header comment
        lines.push(format!(
            "<!-- Generated by `mise generate prompts` from {} -->",
            task.config_source.display()
        ));
        lines.push(
            "<!-- Regenerate with: mise generate prompts -->".to_string(),
        );
        lines.push(String::new());

        // Task description
        if !task.description.is_empty() {
            lines.push(task.description.clone());
            lines.push(String::new());
        }

        // Dependencies
        let deps: Vec<String> = task
            .depends
            .iter()
            .map(|d| d.task.to_string())
            .collect();

        if !deps.is_empty() {
            lines.push("## Prerequisites".to_string());
            lines.push(String::new());
            lines.push(
                "Run these tasks first (in order):".to_string(),
            );
            for dep_name in &deps {
                if let Some(dep_task) = all_tasks.get(dep_name) {
                    let desc = if dep_task.description.is_empty() {
                        String::new()
                    } else {
                        format!(" — {}", dep_task.description)
                    };
                    lines.push(format!("- `mise run {dep_name}`{desc}"));
                } else {
                    lines.push(format!("- `mise run {dep_name}`"));
                }
            }
            lines.push(String::new());
        }

        // Run command
        let scripts = task.run_script_strings();
        if !scripts.is_empty() {
            lines.push("## Command".to_string());
            lines.push(String::new());

            if scripts.len() == 1 {
                lines.push(format!(
                    "Run: `mise run {}`",
                    task.name
                ));
                lines.push(String::new());
                lines.push(format!(
                    "This executes: `{}`",
                    scripts[0].trim()
                ));
            } else {
                lines.push(format!(
                    "Run: `mise run {}`",
                    task.name
                ));
                lines.push(String::new());
                lines.push("This executes the following steps in order:".to_string());
                for (i, script) in scripts.iter().enumerate() {
                    lines.push(format!("{}. `{}`", i + 1, script.trim()));
                }
            }
            lines.push(String::new());
        }

        // Sources (what files trigger this task)
        if !task.sources.is_empty() {
            lines.push("## Relevant files".to_string());
            lines.push(String::new());
            lines.push(
                "This task operates on:".to_string(),
            );
            for source in &task.sources {
                lines.push(format!("- `{source}`"));
            }
            lines.push(String::new());
        }

        // Failure handling
        lines.push("## On failure".to_string());
        lines.push(String::new());
        lines.push(
            "If the command fails, investigate the error output. \
             Attempt to fix the underlying issue and re-run \
             to confirm the fix before reporting completion."
                .to_string(),
        );
        lines.push(String::new());

        lines.join("\n")
    }

    fn render_combined(&self, tasks: &[&Task]) -> String {
        let mut lines = Vec::new();

        lines.push("---".to_string());
        lines.push(
            "description: \"Run project tasks. Use when the user wants to \
             build, test, lint, deploy, or run any project-defined task.\""
                .to_string(),
        );
        lines.push("tools: ['terminal']".to_string());
        lines.push("---".to_string());
        lines.push(String::new());
        lines.push(
            "<!-- Generated by `mise generate prompts` -->".to_string(),
        );
        lines.push(
            "<!-- Regenerate with: mise generate prompts --single -->".to_string(),
        );
        lines.push(String::new());
        lines.push(
            "# Project Tasks".to_string(),
        );
        lines.push(String::new());
        lines.push(
            "This project uses [mise](https://mise.jdx.dev) for task management. \
             Run tasks with `mise run <task-name>`."
                .to_string(),
        );
        lines.push(String::new());
        lines.push("## Available tasks".to_string());
        lines.push(String::new());

        for task in tasks {
            let scripts = task.run_script_strings();
            let desc = if task.description.is_empty() {
                String::new()
            } else {
                format!(" — {}", task.description)
            };
            lines.push(format!(
                "- **{}**{desc}",
                task.name
            ));
            if !scripts.is_empty() {
                for script in &scripts {
                    lines.push(format!("  - `{}`", script.trim()));
                }
            }
        }
        lines.push(String::new());
        lines.push(
            "## On failure".to_string(),
        );
        lines.push(String::new());
        lines.push(
            "If any command fails, investigate the error output. \
             Attempt to fix the underlying issue and re-run \
             to confirm the fix before reporting completion."
                .to_string(),
        );
        lines.push(String::new());

        lines.join("\n")
    }

    fn build_description(task: &Task) -> String {
        let base = if task.description.is_empty() {
            format!("Run the {} task", task.name)
        } else {
            task.description.clone()
        };

        // Build trigger phrases from the task name for better AI discoverability
        let name = &task.name;
        let triggers = match name.as_str() {
            n if n.contains("test") => {
                ". Use when the user says test, run tests, check tests, or verify."
            }
            n if n.contains("lint") => {
                ". Use when the user says lint, check style, or fix formatting."
            }
            n if n.contains("build") => {
                ". Use when the user says build, compile, or make."
            }
            n if n.contains("fmt") || n.contains("format") => {
                ". Use when the user says format, fmt, or fix style."
            }
            n if n.contains("check") => {
                ". Use when the user says check, verify, or validate."
            }
            n if n.contains("deploy") => {
                ". Use when the user says deploy, release, or ship."
            }
            n if n.contains("coverage") || n.contains("cov") => {
                ". Use when the user says coverage, code coverage, or tarpaulin."
            }
            n if n.contains("clean") => {
                ". Use when the user says clean, clear, or reset."
            }
            n if n.contains("doc") => {
                ". Use when the user says docs, documentation, or generate docs."
            }
            _ => "",
        };

        format!("{base}{triggers}")
    }
}

static AFTER_LONG_HELP: &str = color_print::cstr!(
    r#"<bold><underline>Examples:</underline></bold>

    $ <bold>mise generate prompts</bold>
    Generates .github/prompts/*.prompt.md for each visible task

    $ <bold>mise generate prompts --output ./prompts</bold>
    Generates prompt files in a custom directory

    $ <bold>mise generate prompts --single</bold>
    Generates a single combined prompt file

    $ <bold>mise generate prompts --dry-run</bold>
    Prints generated prompts to stdout without writing files

    $ <bold>mise generate prompts --pattern test</bold>
    Only generates prompts for tasks matching "test"
"#
);
