// Based on https://github.com/iki/mise-shim by Jan Killian (MIT License)

#![allow(unknown_lints)]
#![deny(dead_code_pub_in_binary, unreachable_pub)]

use std::env;
use std::path::Path;
use std::process::{Command, ExitCode};

const MISE_SHIM_PATH_ENV: &str = "__MISE_SHIM_PATH";

fn paths_eq(a: &Path, b: &Path) -> bool {
    let lexical_eq = |a: &Path, b: &Path| {
        if cfg!(windows) {
            a.to_string_lossy()
                .eq_ignore_ascii_case(&b.to_string_lossy())
        } else {
            a == b
        }
    };
    if lexical_eq(a, b) {
        return true;
    }
    match (std::fs::canonicalize(a), std::fs::canonicalize(b)) {
        (Ok(a), Ok(b)) => lexical_eq(&a, &b),
        _ => false,
    }
}

fn main() -> ExitCode {
    match run() {
        Ok(code) => ExitCode::from(code as u8),
        Err(err) => {
            eprintln!("{err}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<i32, String> {
    let exe = env::current_exe()
        .map_err(|err| format!("mise-shim: failed to determine executable path: {err}"))?;
    let tool = exe
        .file_stem()
        .ok_or_else(|| "mise-shim: failed to determine tool name from executable path".to_string())?
        .to_os_string();
    if env::var_os(MISE_SHIM_PATH_ENV)
        .as_deref()
        .is_some_and(|previous| paths_eq(Path::new(previous), &exe))
    {
        return Err(format!(
            "mise-shim: recursive shim invocation detected for {}: {}",
            tool.to_string_lossy(),
            exe.display()
        ));
    }

    let args = env::args_os().skip(1);

    // A task stub's launcher and a tool shim are the same executable under different names, so
    // which one this is has to come from what is beside it. `mise x -- <name>` is the shim's job
    // and stays the default: a tool shim has no sibling stub, and a stub that cannot be read is
    // not a reason to stop running as a shim.
    let mut command = match task_stub_beside(&exe) {
        Some(TaskStub { mise_bin, task }) => {
            let mut command = Command::new(mise_bin);
            command.arg("run").arg(task);
            command
        }
        None => {
            let mut command = Command::new("mise");
            command.arg("x").arg("--").arg(&tool);
            command
        }
    };

    let status = command.env(MISE_SHIM_PATH_ENV, &exe).args(args).status();

    match status {
        Ok(status) => Ok(status.code().unwrap_or(1)),
        Err(err) => Err(format!(
            "mise-shim: failed to execute mise: {err}\n\
             Ensure `mise` is installed and available on your PATH.\n\
             See https://mise.jdx.dev for installation instructions."
        )),
    }
}

/// What `mise generate task-stubs` wrote into the stub beside this executable.
struct TaskStub {
    mise_bin: String,
    task: String,
}

/// Read the extensionless stub beside `exe`, if it is one mise generated.
///
/// The stub is the only thing that knows which task this launcher is for and which mise to run it
/// with. Reading it is what lets one `mise-shim.exe` copy serve both jobs, and it is also how
/// `--mise-bin` reaches a native launcher: the launcher is a byte copy of a shared binary and can
/// carry nothing of its own.
fn task_stub_beside(exe: &Path) -> Option<TaskStub> {
    let stub = exe.with_extension("");
    if stub == exe {
        // No extension to drop, so `stub` is this executable. Reading ourselves would at best
        // fail the marker check, and a launcher named after its own stub is not a shape mise
        // generates.
        return None;
    }
    parse_task_stub(&std::fs::read_to_string(stub).ok()?)
}

/// Parse the stub body `generate task-stubs` writes, or `None` for anything else.
///
/// The shape is fixed by the generator:
///
/// ```sh
/// #!/bin/sh
/// # generated by mise task-stubs
/// exec <mise-bin> run <task> "$@"
/// ```
///
/// Deliberately strict. A stub that does not match is a file mise did not write -- or wrote in a
/// shape this copy predates -- and running the wrong task is worse than falling back to the shim
/// behaviour, which is what a `None` here does.
fn parse_task_stub(contents: &str) -> Option<TaskStub> {
    let mut lines = contents.lines();
    if lines.next()? != "#!/bin/sh" {
        return None;
    }
    if lines.next()? != "# generated by mise task-stubs" {
        return None;
    }
    let command = lines.next()?;
    if lines.next().is_some() {
        return None;
    }
    let command = command.strip_prefix("exec ")?.strip_suffix(" \"$@\"")?;
    let (mise_bin, rest) = split_first_word(command)?;
    // The task name is interpolated raw by the generator, so whatever is left is it verbatim --
    // no unquoting, and no splitting on a space a task name is allowed to contain.
    let task = rest.strip_prefix("run ")?;
    if mise_bin.is_empty() || task.is_empty() {
        return None;
    }
    Some(TaskStub {
        mise_bin,
        task: task.to_string(),
    })
}

/// Split off the first shell word of the stub's `exec` line, returning it and the rest.
///
/// Only the two shapes `shell_words::quote` produces are accepted: a bare word, and a
/// single-quoted one where an embedded `'` is written `'\''`. Anything else -- a double quote, a
/// backslash escape, an unterminated quote -- is not something mise wrote, so it is rejected
/// rather than guessed at. Written out here because this crate has no dependencies and is not
/// worth giving one for three cases.
fn split_first_word(line: &str) -> Option<(String, &str)> {
    let Some(mut rest) = line.strip_prefix('\'') else {
        let (word, rest) = line.split_once(' ')?;
        if word.contains(['\'', '"', '\\']) {
            return None;
        }
        return Some((word.to_string(), rest));
    };
    let mut word = String::new();
    loop {
        let (chunk, after) = rest.split_once('\'')?;
        word.push_str(chunk);
        match after.strip_prefix(r"\''") {
            // `'\''` -- the quoted word continues with a literal `'`.
            Some(next) => {
                word.push('\'');
                rest = next;
            }
            // The closing quote, which has to be followed by the separator.
            None => return Some((word, after.strip_prefix(' ')?)),
        }
    }
}

#[cfg(test)]
mod task_stub_tests {
    use super::*;

    /// Build a stub body the way `mise generate task-stubs` does, so these tests move if it does.
    /// `mise_bin` is passed already quoted, matching the generator's `shell_words::quote`.
    fn stub(mise_bin: &str, task: &str) -> String {
        format!("#!/bin/sh\n# generated by mise task-stubs\nexec {mise_bin} run {task} \"$@\"")
    }

    #[test]
    fn reads_the_default_stub() {
        let parsed = parse_task_stub(&stub("mise", "hello")).unwrap();
        assert_eq!(parsed.mise_bin, "mise");
        assert_eq!(parsed.task, "hello");
    }

    #[test]
    fn reads_a_mise_bin_flag() {
        // The whole reason the launcher reads the stub: it is a byte copy of a shared binary, so
        // `--mise-bin` can only reach it through here.
        let parsed = parse_task_stub(&stub("./bin/mise", "build")).unwrap();
        assert_eq!(parsed.mise_bin, "./bin/mise");
        assert_eq!(parsed.task, "build");
    }

    #[test]
    fn unquotes_a_mise_bin_the_generator_had_to_quote() {
        // `shell_words::quote` output for a path with a space, and for one with a quote in it.
        let parsed = parse_task_stub(&stub("'/opt/my mise/mise'", "test")).unwrap();
        assert_eq!(parsed.mise_bin, "/opt/my mise/mise");

        let parsed = parse_task_stub(&stub(r"'/opt/it'\''s/mise'", "test")).unwrap();
        assert_eq!(parsed.mise_bin, "/opt/it's/mise");
    }

    #[test]
    fn keeps_a_task_name_verbatim() {
        // The generator interpolates the display name raw, so a name containing a space is not
        // two words and must not be split.
        let parsed = parse_task_stub(&stub("mise", "run tests")).unwrap();
        assert_eq!(parsed.task, "run tests");
        // A name that repeats the separator is still the whole remainder.
        let parsed = parse_task_stub(&stub("mise", "a run b")).unwrap();
        assert_eq!(parsed.task, "a run b");
    }

    #[test]
    fn a_file_mise_did_not_write_is_not_a_stub() {
        // The controls. A false positive here runs a task the file never named, so every part of
        // the shape has to be load-bearing.
        for contents in [
            "",
            // The pre-marker spelling, which is also what `generate_legacy` still writes: an
            // older mise wrote this, and nothing in it says so, hence the marker.
            "#!/bin/sh\nexec mise run hello \"$@\"",
            "#!/bin/bash\n# generated by mise task-stubs\nexec mise run hello \"$@\"",
            "#!/bin/sh\n# hand written\nexec mise run hello \"$@\"",
            // Arguments are the caller's, not the stub's.
            "#!/bin/sh\n# generated by mise task-stubs\nexec mise run hello",
            // Trailing content -- someone appended to it, so it is no longer only ours.
            "#!/bin/sh\n# generated by mise task-stubs\nexec mise run hello \"$@\"\necho done",
            // Missing the subcommand, an empty task, an empty bin.
            "#!/bin/sh\n# generated by mise task-stubs\nexec mise hello \"$@\"",
            "#!/bin/sh\n# generated by mise task-stubs\nexec mise run  \"$@\"",
            // Quoting shapes the generator does not produce.
            "#!/bin/sh\n# generated by mise task-stubs\nexec \"mise\" run hello \"$@\"",
            "#!/bin/sh\n# generated by mise task-stubs\nexec 'mise run hello \"$@\"",
        ] {
            assert!(parse_task_stub(contents).is_none(), "{contents:?}");
        }
    }

    #[test]
    fn a_word_needs_a_separator_after_it() {
        assert_eq!(split_first_word("mise"), None);
        assert_eq!(split_first_word("'mise'"), None);
        assert_eq!(
            split_first_word("mise rest"),
            Some(("mise".to_string(), "rest"))
        );
    }
}
