#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

ROOT="$(cd "$SCRIPT_DIR"/.. && pwd)"
TEST="$1"

setup_env() {
	export ROOT
	export PATH="$ROOT/target/debug:$PATH"
	export RTX_USE_TOML="0"
	export RTX_DATA_DIR="$HOME/.rtx/e2e"
	export RTX_CACHE_DIR="$HOME/.rtx/e2e/cache"
	export RTX_CONFIG_DIR="$HOME/.rtx/e2e/config"
	export RTX_DEFAULT_TOOL_VERSIONS_FILENAME=.e2e-tool-versions
	export RTX_DEFAULT_CONFIG_FILENAME=.e2e.rtx.toml
	export RTX_CONFIG_FILE="$ROOT/e2e/.config/rtx/config.toml"
	export RTX_TRUSTED_CONFIG_PATHS="$ROOT/e2e"
	export RTX_YES="1"
	unset GOPATH
}

setup_config_files() {
	mkdir -p "$ROOT/e2e/cd/18"
	cp "$ROOT/e2e/config/".e2e.* "$ROOT/e2e/"
	cp "$ROOT/e2e/config/"{.node-version,.alternate-tool-versions,.test-env,pyproject.toml} "$ROOT/e2e/"
	cp "$ROOT/e2e/config/cd/".e2e.* "$ROOT/e2e/cd/"
	cp "$ROOT/e2e/config/cd/18/".e2e.* "$ROOT/e2e/cd/18"
}

run_test() {
	echo "Running $TEST"
	rm -f "$RTX_CONFIG_FILE"
	cd "$(dirname "$TEST")"
	rtx i

	"./$(basename "$TEST")"
}

setup_env
setup_config_files
run_test
