#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

mise plugins uninstall tiny
mise p ln "$ROOT/test/data/plugins/tiny"
assert_contains "mise p" "tiny"
assert_fail "mise p link $ROOT/test/data/plugins/tiny"
mise plugins link -f "$ROOT/test/data/plugins/tiny"
