#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

unset MISE_GLOBAL_CONFIG_FILE
unset MISE_CONFIG_FILE

assert_contains "mise global node 20.0.0" "~/.mise/e2e/config/config.toml"
MISE_ASDF_COMPAT=1 assert_contains "mise global node 20.0.0" "~/.e2e-tool-versions"
MISE_CONFIG_FILE=$HOME/.e2e-tool-versions assert_contains "mise global node 20.0.0" "~/.e2e-tool-versions"
MISE_GLOBAL_CONFIG_FILE=$HOME/.e2e-tool-versions assert_contains "mise global node 20.0.0" "~/.e2e-tool-versions"

rm -f ~/.e2e-tool-versions ~/.mise/e2e/config/config.toml
