#!/usr/bin/env bash
set -euo pipefail

assert() {
  local actual
  actual="$($*)"
  if [[ "$actual" != "$2" ]]; then
    echo "Expected '$2' but got '$actual'"
    exit 1
  fi
}

eval "$(rtx activate bash)" && eval "$(rtx hook-env)"
rtx plugin install https://github.com/kachick/asdf-zigmod
rtx x --install-missing zigmod@latest -- zigmod version
