#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/assert.sh"

export RTX_EXPERIMENTAL=1

system_node="$(which node)"
rtx_node="$(rtx which node)"

assert "rtx x node@system nodejs@system -- which node" "$system_node"
assert "rtx x node -- which node" "$rtx_node"
