#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

rtx i
rtx uninstall tiny
export CLICOLOR=0
assert_contains "rtx ls tiny" "3.1.0 (missing)"

rtx i tiny@1 tiny@2.0 tiny@2.1
assert_contains "rtx ls tiny" "1.0.1"
assert_contains "rtx ls tiny" "2.0.1"
assert_contains "rtx ls tiny" "2.1.0"

rtx rm -a tiny@2
assert_contains "rtx ls tiny" "1.0.1"
assert_not_contains "rtx ls tiny" "2.0.1"
assert_not_contains "rtx ls tiny" "2.1.0"

rtx rm -a tiny
assert_not_contains "rtx ls tiny" "1.0.1"
assert_not_contains "rtx ls tiny" "2.0.1"
assert_not_contains "rtx ls tiny" "2.1.0"
