#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

export MISE_EXPERIMENTAL=1

cat <<EOF >.bun-version
1.0.17
EOF

mise i bun
assert_contains "mise x bun -- bun -v" "1.0.17"
assert_contains "mise x bun -- bunx oclif --version" "oclif"
rm .bun-version
