#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

export MISE_EXPERIMENTAL=1

INSTALLED_PIPX="false"

readonly PIPX_VENV="${TMPDIR:-/tmp}/mise-pipx-venv-testing/pipx"

if ! command -v pipx >/dev/null; then
  INSTALLED_PIPX="true"
  if [[ ! -d "$PIPX_VENV" ]]; then
    python3 -m venv "$PIPX_VENV" >/dev/null
  fi

  # shellcheck source=/dev/null
  source "$PIPX_VENV/bin/activate" >/dev/null

  python3 -m pip install pipx >/dev/null

  pipx_cleanup() {
    if [[ "$INSTALLED_PIPX" = "true" ]]; then
      rm -rf "$PIPX_VENV"
    fi
  }

  trap 'pipx_cleanup' EXIT
fi

assert "mise x pipx:black@22.6.0 -- black --version | head -1" "black, 22.6.0 (compiled: no)"
assert "mise x pipx:psf/black@24.3.0 -- black --version | head -1" "black, 24.3.0 (compiled: no)"
assert "mise x pipx:git+https://github.com/psf/black.git@24.2.0 -- black --version | head -1" "black, 24.2.0 (compiled: no)"
