#!/usr/bin/env bash
set -euo pipefail

assert() {
	local actual
	# shellcheck disable=SC2048
	actual="$($*)"
	if [[ "$actual" != "$2" ]]; then
		echo "Expected '$2' but got '$actual'"
		exit 1
	fi
}

eval "$(rtx activate bash)" && _rtx_hook
rtx doctor
