#!/usr/bin/env bash
set -euo pipefail

assert() {
	local actual
	actual="$($1)"
	if [[ "$actual" != "$2" ]]; then
		echo "Expected '$2' but got '$actual'"
		exit 1
	fi
}

rtx local tiny@sub-1:latest
assert "rtx current tiny" "2.1.0"
rtx local tiny@sub-1:lts
assert "rtx current tiny" "2.1.0"
rtx local tiny@sub-0.1:3.1
assert "rtx current tiny" "3.0.1"
rtx local tiny@latest
