#!/usr/bin/env bash
set -euo pipefail

assert() {
  local actual
  actual="$($*)"
  if [[ "$actual" != "$2" ]]; then
    echo "Expected '$2' but got '$actual'"
    exit 1
  fi
}

rtx i --raw -f tiny@1 tiny@2 tiny@3
RTX_RAW=1 rtx i -f tiny@1 tiny@2 tiny@3
