#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

cat <<EOF >.node-version
18
EOF

cat <<EOF >.bun-version
1.0.17
EOF

mise i
assert_contains "mise x bun -- bun -v" "1.0.17"
assert_contains "mise x bun -- bunx oclif --version" "oclif"
