#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

export MISE_EXPERIMENTAL=1
eval "$(mise activate bash --shims)"
mise use go@prefix:1.20

assert "mise x go:github.com/DarthSim/hivemind@v1.1.0 -- hivemind --version" "Hivemind version 1.1.0"
assert "mise x go:github.com/go-task/task/v3/cmd/task@v3.34.1 -- task --version" "Task version: v3.34.1 (h1:yAAxUM54zoaHv+OtDnGgkWSVeiRuaOCn1lPUXPQQA0o=)"
# See https://github.com/jdx/mise/issues/1667
assert "mise x go:github.com/jdx/go-example@e16a340 -- go-example" "hello world"

# Required to properly cleanup as go installs read-only sources
chmod -R +w ~/go
