#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/assert.sh"

rtx cache clean
rtx trust .e2e.rtx.toml
rtx i nodejs
eval "$(rtx env -s bash)"
assert "node -v" "v18.0.0"
rtx i nodejs@16.0.0
eval "$(rtx env -s bash nodejs@16.0.0)"
assert "node -v" "v16.0.0"
assert "rtx x -- env | grep FOO_FROM_FILE" "FOO_FROM_FILE=foo_from_file"
