#!/usr/bin/env bash
set -euo pipefail
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

export MISE_EXPERIMENTAL=1

cat <<EOF >.deno-version
1.35.3
EOF
mise i deno
assert_contains "mise x deno -- deno -V" "deno 1.35.3"
rm .deno-version
