#!/usr/bin/env bash
set -e
# shellcheck source-path=SCRIPTDIR
source "$(dirname "$0")/assert.sh"

export MISE_EXPERIMENTAL=1
export MISE_GO_DEFAULT_PACKAGES_FILE="$ROOT/e2e/.default-go-packages"

cat >"$MISE_GO_DEFAULT_PACKAGES_FILE" <<EOF
github.com/jdx/go-example # comment
EOF

mise use golang@prefix:1.20
assert_contains "mise x -- go version" "go version go1.20"

rm "$MISE_GO_DEFAULT_PACKAGES_FILE"
chmod -R u+w "$MISE_DATA_DIR/installs/go"
