#!/usr/bin/env bash

#################################################################################
# Prerequisites
#################################################################################

# Only create the ssh key if the CI env var is set
if [ -n "$CI" ]; then
  TEMP_SSH_KEY="temp_ssh_key"
  ssh-keygen -t ed25519 -f "$TEMP_SSH_KEY" -N ""
  eval "$(ssh-agent -s)"
  ssh-add "$TEMP_SSH_KEY"
else
  echo "Skipping test as CI env var is not set"
fi

cargo init --name hello_cargo

#################################################################################
# Test remote tasks with no ref
#################################################################################

cat <<EOF >mise.toml
[tasks.remote_lint_ssh_latest]
file  = "git::ssh://git@github.com:jdx/mise.git//xtasks/lint/clippy"
EOF

assert_contains "mise tasks" "remote_lint_ssh_latest"
assert_succeed "mise run remote_lint_ssh_latest" # Remote task should be downloaded

mise cache clear # Clear cache to force redownload

assert_succeed "MISE_TASK_REMOTE_NO_CACHE=true mise run remote_lint_ssh_latest" # Remote task should be redownloaded

assert_succeed "mise run remote_lint_ssh_latest --no-cache" # Remote task should be redownloaded

assert_succeed "mise run remote_lint_ssh_latest" # Cache should be used

#################################################################################
# Test remote tasks with with ref
#################################################################################

cat <<EOF >mise.toml
[tasks.remote_lint_ssh_ref]
file  = "git::ssh://git@github.com:jdx/mise.git//xtasks/lint/clippy?ref=v2025.1.17"
EOF

assert_contains "mise tasks" "remote_lint_ssh_ref"
assert_succeed "mise run remote_lint_ssh_ref" # Remote task should be downloaded

mise cache clear # Clear cache to force redownload

assert_succeed "MISE_TASK_REMOTE_NO_CACHE=true mise run remote_lint_ssh_ref" # Remote task should be redownloaded

assert_succeed "mise run remote_lint_ssh_ref --no-cache" # Remote task should be redownloaded

assert_succeed "mise run remote_lint_ssh_ref" # Cache should be used
