#!/usr/bin/env bash

cat <<'TOML' >mise.toml
[task_config]
includes = ["tasks.toml", "root-tasks"]
TOML

cat <<'TOML' >tasks.toml
[root-file-task]
run = 'echo "root file task"'
TOML

mkdir -p root-tasks
cat <<'SCRIPT' >root-tasks/root-dir-task
#!/usr/bin/env bash
echo "root dir task"
SCRIPT
chmod +x root-tasks/root-dir-task

mkdir -p .mise/tasks
cat <<'SCRIPT' >.mise/tasks/default-task
#!/usr/bin/env bash
echo "default task"
SCRIPT
chmod +x .mise/tasks/default-task

cat <<'TOML' >mise.local.toml
[task_config]
includes = ["tasks.local.toml", "local-tasks"]
includes_mode = "extend"
TOML

cat <<'TOML' >tasks.local.toml
[local-file-task]
run = 'echo "local file task"'
TOML

mkdir -p local-tasks
cat <<'SCRIPT' >local-tasks/local-dir-task
#!/usr/bin/env bash
echo "local dir task"
SCRIPT
chmod +x local-tasks/local-dir-task

mise tasks ls >tasks.out
assert_not_contains "cat tasks.out" "default-task"
assert_contains "cat tasks.out" "root-file-task"
assert_contains "cat tasks.out" "root-dir-task"
assert_contains "cat tasks.out" "local-file-task"
assert_contains "cat tasks.out" "local-dir-task"

cat <<'TOML' >mise.local.toml
[task_config]
includes = ["tasks.local.toml", "local-tasks"]
TOML

mise tasks ls >tasks.out
assert_not_contains "cat tasks.out" "default-task"
assert_not_contains "cat tasks.out" "root-file-task"
assert_not_contains "cat tasks.out" "root-dir-task"
assert_contains "cat tasks.out" "local-file-task"
assert_contains "cat tasks.out" "local-dir-task"

cat <<'TOML' >mise.toml
[task_config]
includes = ["tasks.toml", "root-tasks"]
includes_mode = "extend"
TOML

mise tasks ls >tasks.out
assert_not_contains "cat tasks.out" "default-task"
assert_not_contains "cat tasks.out" "root-file-task"
assert_not_contains "cat tasks.out" "root-dir-task"
assert_contains "cat tasks.out" "local-file-task"
assert_contains "cat tasks.out" "local-dir-task"

cat <<'TOML' >mise.local.toml
[task_config]
includes = ["tasks.local.toml", "local-tasks"]
includes_mode = "extend"
TOML

mise tasks ls >tasks.out
assert_contains "cat tasks.out" "default-task"
assert_contains "cat tasks.out" "root-file-task"
assert_contains "cat tasks.out" "root-dir-task"
assert_contains "cat tasks.out" "local-file-task"
assert_contains "cat tasks.out" "local-dir-task"

cat <<'TOML' >mise.toml
[env]
ROOT_CONFIG = "1"
TOML

cat <<'TOML' >mise.prod.toml
[task_config]
includes = ["prod-tasks"]
includes_mode = "extend"
TOML

mkdir -p prod-tasks
cat <<'SCRIPT' >prod-tasks/prod-dir-task
#!/usr/bin/env bash
echo "prod dir task"
SCRIPT
chmod +x prod-tasks/prod-dir-task

cat <<'TOML' >mise.ci.toml
[task_config]
includes = ["ci-tasks"]
TOML

mkdir -p ci-tasks
cat <<'SCRIPT' >ci-tasks/ci-dir-task
#!/usr/bin/env bash
echo "ci dir task"
SCRIPT
chmod +x ci-tasks/ci-dir-task

cat <<'TOML' >mise.local.toml
[task_config]
includes = ["tasks.local.toml", "local-tasks"]
includes_mode = "extend"
TOML

MISE_ENV=prod,ci mise tasks ls >tasks.out
assert_not_contains "cat tasks.out" "default-task"
assert_not_contains "cat tasks.out" "root-file-task"
assert_not_contains "cat tasks.out" "root-dir-task"
assert_not_contains "cat tasks.out" "prod-dir-task"
assert_contains "cat tasks.out" "ci-dir-task"
assert_not_contains "cat tasks.out" "local-file-task"
assert_not_contains "cat tasks.out" "local-dir-task"
