#!/usr/bin/env bash

# MatrixRef: V02,I04 / C15
cat <<EOF >mise.toml
[task_config]
includes = [
	"tasks.toml",
	"mytasks",
]
[tasks.lint]
run = 'echo "linting!"'
EOF

cat <<EOF >tasks.toml
[test]
run = 'echo "testing!"'
[test-with-args]
run = 'echo "{{arg()}} {{flag(name="force")}} {{option(name="user")}}"'
depends = ["test -v", "test"]
EOF

mkdir -p .mise/tasks
cat <<'EOF' >.mise/tasks/do-not-show
#!/usr/bin/env bash
EOF
chmod +x .mise/tasks/do-not-show

mkdir -p mytasks
cat <<'EOF' >mytasks/filetask2
#!/usr/bin/env bash
EOF
chmod +x mytasks/filetask2

cat <<'EOF' >mytasks/filetask3.sh
#!/usr/bin/env bash
EOF
chmod +x mytasks/filetask3.sh

mkdir -p .config/mise/conf.d
cat <<'EOF' >.config/mise/conf.d/confdtask-config.toml
[tasks.confdtask]
run = 'echo "confdtask"'
EOF

assert "mise tasks ls" "confdtask
filetask2
filetask3
lint
test
test-with-args"

assert "mise tasks -x ls" "confdtask          ./.config/mise/conf.d/confdtask-config.toml:1
filetask2          ./mytasks/filetask2:1
filetask3          ./mytasks/filetask3.sh:1
lint               ./mise.toml:6
test               ./tasks.toml
test-with-args     ./tasks.toml"

assert "mise tasks ls --json | jq 'length'" "6"
for task in confdtask filetask2 filetask3 lint test test-with-args; do
	assert "mise tasks ls --json | jq -r '.[] | select(.name==\"$task\") | .interactive'" "false"
done
