#!/bin/bash
set -e

# add this directory to `$PATH` to automatically build/run chim
# when chims are called in shebangs

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cargo run --all-features --manifest-path "$SCRIPT_DIR/../Cargo.toml" -- "$@"
