#!/usr/bin/env bash

mkdir -p "$MISE_DATA_DIR/installs/github-jdx-mise-test-fixtures/1.0.0/bin"
mkdir -p "$MISE_DATA_DIR/installs/github-jdx-mise-test-fixtures/latest/bin"
cat <<'EOF' >"$MISE_DATA_DIR/installs/.mise-installs.toml"
[github-jdx-mise-test-fixtures]
short = "github:jdx/mise-test-fixtures"
full = "github:jdx/mise-test-fixtures"
explicit_backend = true
EOF

output=$(mise ls github:jdx/mise-test-fixtures)
latest_link="$MISE_DATA_DIR/installs/github-jdx-mise-test-fixtures/latest"
link_target=$(readlink "$latest_link")
assert "test '$link_target' = ./1.0.0"
assert_not_contains "echo '$output'" "latest"
assert_contains "echo '$output'" "1.0.0"
