description = "Code review for the age of AI"
test = { cmd = "gt --version", expected = "{{version}}" }
version_order = "semver"

bins = ["gt"]
[[backends]]
full = "github:withgraphite/homebrew-tap"

[[backends]]
full = "npm:@withgraphite/graphite-cli"
