bins = [
  "redis-benchmark",
  "redis-check-aof",
  "redis-check-rdb",
  "redis-cli",
  "redis-sentinel",
  "redis-server",
]
description = "Cache & in-memory datastore"
test = { cmd = "redis-server --version", expected = "v={{version}}" }
version_order = "semver"

[[backends]]
full = "conda:redis-server"
platforms = ["linux", "macos"]

[[backends]]
full = "vfox:mise-plugins/vfox-redis"

[[backends]]
full = "asdf:mise-plugins/mise-redis"
