backends = [
  "aqua:SonarSource/sonar-scanner-cli",
  "asdf:virtualstaticvoid/asdf-sonarscanner",
]
bins = ["sonar-scanner", "sonar-scanner-debug"]
description = "Scanner CLI for SonarQube (Server, Cloud)"
test = { cmd = "sonar-scanner --version", expected = "SonarScanner CLI {{version}}" }
version_order = "source"
