backends = ["github:aome510/spotify-player"]
bins = ["spotify_player"]
description = "A Spotify player in the terminal with full feature parity"
test = { cmd = "spotify_player --version", expected = "spotify_player {{version}}" }
version_order = "semver"
