#!/usr/bin/env zsh
set -e

export MISE_EXPERIMENTAL=1

eval "$(direnv hook zsh)"
eval "$(mise activate zsh --status)"
_mise_hook && direnv allow && _direnv_hook

assert_go_version() {
  local expected="$1"
  if [[ "$GOPATH" != "$expected" ]]; then
    echo "Invalid GOPATH: $GOPATH, expected: $expected"
    exit 1
  fi
}

mise i golang@1.18.10 golang@1.19.5 && _mise_hook
#assert_gopath "$MISE_DATA_DIR/installs/golang/1.19.5/packages"
cd mise-direnv-break-path-source && _mise_hook
direnv allow && _direnv_hook
#assert_gopath "$MISE_DATA_DIR/installs/golang/1.18.10/packages"
cd ../mise-direnv-break-path-target && _mise_hook
direnv allow && _direnv_hook
#assert_gopath "$MISE_DATA_DIR/installs/golang/1.19.5/packages"
mise -v # should not fail, the bug is that PATH gets set to a junk value and this does not work
