# @generated by usage-argv for `mise __complete_word__ --shell bash`

_usage_complete_mise() {
    local __usage_out __usage_line __usage_files= __usage_extensions=
    # Truncated here rather than passed with an offset: every shell counts a cursor in its own
    # units — characters in a UTF-8 locale for bash and zsh, characters for fish and PowerShell —
    # and a number that means one thing here and another there is a bug waiting for a non-ASCII
    # command line. Cut with the shell's own offset, the units cancel out and what arrives is
    # exactly the text before the cursor.
    __usage_out="$(command 'mise' __complete_word__ --shell bash \
        --line "${COMP_LINE:0:$COMP_POINT}" 2>/dev/null)" || return 1

    COMPREPLY=()
    while IFS= read -r __usage_line; do
        case "$__usage_line" in
            $'\001files') __usage_files=any ;;
            $'\001dirs') __usage_files=dirs ;;
            $'\001executables') __usage_files=executables ;;
            $'\001commands') __usage_files=commands ;;
            $'\001extensions\t'*)
                __usage_files=extensions
                __usage_extensions="${__usage_line#*$'\t'}"
                ;;
            '') ;;
            *) COMPREPLY+=("$__usage_line") ;;
        esac
    done <<< "$__usage_out"

    if [[ -n $__usage_files ]]; then
        # Set here rather than on `complete`, because whether this position takes a path is not
        # known until the answer comes back. It is what makes bash append a `/` to a directory
        # and stop escaping what it should not.
        [[ $__usage_files == commands ]] || compopt -o filenames 2>/dev/null
        local __usage_cur="${COMP_WORDS[COMP_CWORD]}" __usage_path
        local -a __usage_paths=()
        if [[ $__usage_files == commands ]]; then
            while IFS= read -r __usage_path; do __usage_paths+=("$__usage_path"); done \
                < <(compgen -c -- "$__usage_cur")
        elif [[ $__usage_files == executables ]]; then
            while IFS= read -r __usage_path; do
                [[ -d "$__usage_path" || -x "$__usage_path" ]] && __usage_paths+=("$__usage_path")
            done < <(compgen -f -- "$__usage_cur")
        elif [[ $__usage_files == dirs ]]; then
            while IFS= read -r __usage_path; do __usage_paths+=("$__usage_path"); done \
                < <(compgen -d -- "$__usage_cur")
        else
            while IFS= read -r __usage_path; do
                if [[ $__usage_files != extensions || -d "$__usage_path" ]]; then
                    __usage_paths+=("$__usage_path")
                    continue
                fi
                local __usage_extension
                while IFS= read -r __usage_extension; do
                    [[ "$__usage_path" == *."$__usage_extension" ]] && {
                        __usage_paths+=("$__usage_path")
                        break
                    }
                done < <(tr '\t' '\n' <<< "$__usage_extensions")
            done < <(compgen -f -- "$__usage_cur")
        fi
        # Guarded, because an empty array expands to one empty word in older bash.
        (( ${#__usage_paths[@]} )) && COMPREPLY+=("${__usage_paths[@]}")
    fi
}
complete -F _usage_complete_mise 'mise'
