backends = ["npm:playwright"]
bins = ["playwright"]
description = "A high-level API to automate web browsers"
test = { cmd = "playwright --version", expected = "Version {{version}}" }
version_order = "semver"
