#!/usr/bin/env bash

cat <<EOF >mise.toml
[plugins]
tiny-ref = "https://github.com/mise-plugins/rtx-tiny#c532b140abd4ca00d3e76651b9bd32a980bd483c"
aws-sso-cli = "https://github.com/mise-plugins/mise-aws-sso-cli"
EOF

assert_contains "mise latest tiny-ref" "3.1.0"
assert_matches "mise latest aws-sso-cli" '^[0-9]+\.[0-9]+\.[0-9]+'
