#!/usr/bin/env bash

assert_fail "mise current tiny"

mise i tiny

mise local tiny@sub-1:latest
assert "mise current tiny" "2.1.0"

mise local tiny@sub-1:lts
assert "mise current tiny" "2.1.0"

mise local tiny@sub-0.1:3.1
assert "mise current tiny" "3.0.1"
