#!/usr/bin/env bash
set -euo pipefail

mise install node@20.0.0 node@18.0.0
# shellcheck disable=SC1090
eval "$(mise activate -s bash --status)"
_mise_hook

#mise install
test "$(node -v)" = "v20.0.0"

cd 18 && _mise_hook
#mise install
test "$(node -v)" = "v18.0.0"

cd .. && _mise_hook
test "$(node -v)" = "v20.0.0"
