#!/usr/bin/env bash
set -euo pipefail

rtx install nodejs@20.0.0 nodejs@18.0.0
# shellcheck disable=SC1090
eval "$(rtx activate -s bash --status)"
_rtx_hook

#rtx install
test "$(node -v)" = "v20.0.0"

cd 18 && _rtx_hook
#rtx install
test "$(node -v)" = "v18.0.0"

cd .. && _rtx_hook
test "$(node -v)" = "v20.0.0"
