name: autofix.ci

on:
  workflow_call:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  MISE_TRUSTED_CONFIG_PATHS: ${{ github.workspace }}
  MISE_EXPERIMENTAL: 1
  MISE_LOCKFILE: 1
  RUST_BACKTRACE: 1
  NPM_CONFIG_FUND: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  autofix:
    if: github.actor != 'renovate[bot]' && github.actor != 'mend[bot]'
    runs-on: namespace-profile-endev-linux-amd64;overrides.cache-tag=mise-pr-rust-linux
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: namespacelabs/nscloud-cache-action@15799a6b54e5765f85b2aac25b3f0df43ed571c0 # v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/.global-cache
            ~/.cache/sccache
      - uses: taiki-e/install-action@51cd0b8c0499559d9a4d75c0f5c67bec3a894ec8 # v2
        with: { tool: sccache }
      - name: Configure sccache
        run: |
          export RUSTC_WRAPPER=sccache
          export SCCACHE_DIR="$HOME/.cache/sccache"
          export SCCACHE_CACHE_SIZE=20G
          {
            echo "RUSTC_WRAPPER=$RUSTC_WRAPPER"
            echo "SCCACHE_DIR=$SCCACHE_DIR"
            echo "SCCACHE_CACHE_SIZE=$SCCACHE_CACHE_SIZE"
          } >> "$GITHUB_ENV"
          sccache --zero-stats
      - run: |
          cargo build --all-features
          echo "$PWD/target/debug" >> "$GITHUB_PATH"
      - uses: ./.github/actions/mise-tools
      - run: mise x -- bun i
      - run: mise run render
      - run: mise run lint-fix
      - run: mise --cd crates/vfox run lint-fix
      - run: sccache --show-stats
        if: always()
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
#  windows:
#    runs-on: windows-latest
#    timeout-minutes: 30
#    steps:
#      - run: git config --global core.autocrlf false
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
#      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2
#        with:
#          shared-key: autofix
#      - run: |
#          cargo build
#          Add-Content $env:GITHUB_PATH "$env:GITHUB_WORKSPACE\target\debug"
#        shell: pwsh
#      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
#        with:
#          key: ${{ runner.os }}-${{ runner.arch }}-mise-tools-${{ hashFiles('mise.lock') }}
#          path: |
#            ~/.local/share/mise
#            ~/.cache/mise
#      - run: mise install
#      - run: mise x -- npm i
#      #- run: mise run render
#      - run: mise run lint-fix
#      - run: mise --cd crates/vfox run lint-fix
#      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
