name: release-fig
on:
  push:
    tags:
      - "v*.0" ## Only run the action on new versions once per month, this prevents useless runs of the action
  workflow_dispatch:

jobs:
  push-to-fig-autocomplete:
    ## if github.repository == 'jdx/mise'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.MISE_GH_TOKEN }}
      - run: mkdir -p "$HOME/bin" && echo "$HOME/bin" >> "$GITHUB_PATH"
      - run: cargo build --all-features && cp target/debug/mise "$HOME"/bin
      - uses: ./.github/actions/mise-tools
      - run: mise x -- bun i
      - run: mise run render:fig
      - name: Create Autocomplete PR ## Create the autocomplete PR using this action
        uses: withfig/push-to-fig-autocomplete-action@fb320c27ec12b225b9446373aa30b7d9c0c1eae8 # v2
        with:
          token: ${{ secrets.MISE_GH_TOKEN }}
          autocomplete-spec-name: mise
          spec-path: tasks/fig/src/mise.ts
          pr-body: "Automated PR for latest mise release by https://github.com/jdx/mise"
