name: release-plz

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: release-plz

env:
  MISE_EXPERIMENTAL: 1
  NPM_CONFIG_FUND: false
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.MISE_GH_TOKEN || secrets.GITHUB_TOKEN }}

jobs:
  release-plz:
    if: github.repository == 'jdx/mise'
    timeout-minutes: 20
    runs-on: namespace-profile-endev-linux-amd64;overrides.cache-tag=mise-release-plz-rust-linux
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.MISE_GH_TOKEN }}
      - uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.MISE_GPG_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - uses: namespacelabs/nscloud-cache-action@15799a6b54e5765f85b2aac25b3f0df43ed571c0 # v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/.global-cache
            ~/.cache/sccache
      - uses: taiki-e/install-action@51cd0b8c0499559d9a4d75c0f5c67bec3a894ec8 # v2
        with: { tool: sccache }
      - name: Configure sccache
        run: |
          export RUSTC_WRAPPER=sccache
          export SCCACHE_DIR="$HOME/.cache/sccache"
          export SCCACHE_CACHE_SIZE=20G
          {
            echo "RUSTC_WRAPPER=$RUSTC_WRAPPER"
            echo "SCCACHE_DIR=$SCCACHE_DIR"
            echo "SCCACHE_CACHE_SIZE=$SCCACHE_CACHE_SIZE"
          } >> "$GITHUB_ENV"
          sccache --zero-stats
      - run: mkdir -p "$HOME/bin" && echo "$HOME/bin" >> "$GITHUB_PATH"
      - run: cargo build --all-features && cp target/debug/mise "$HOME"/bin
      - uses: ./.github/actions/mise-tools
      - run: mise x -- bun i
      - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
        id: crates-io-auth
      - run: mise run release-plz
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.crates-io-auth.outputs.token }}
      - run: sccache --show-stats
        if: always()
